# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3417f1ce-3aca-4d17-9f06-f26f994563f1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3417f1ce-3aca-4d17-9f06-f26f994563f1".device = "/dev/disk/by-uuid/3417f1ce-3aca-4d17-9f06-f26f994563f1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3F40-7606";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-543b58be-3e42-40d1-b214-7103c755dbcb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
